blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('post/<slug>', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('delete/<slug>', views.delete_post, name='delete_post'),
    path('edit/<slug>', views.edit_post, name='edit_post'),
    path('like/<slug>', views.like, name='like'),
    path('dislike/<slug>', views.dislike, name='dislike'),
    path('comment_delete/<int:pk>', views.comment_delete, name='comment_delete'),
    path('comment_edit/<int:pk>', views.comment_edit, name='comment_edit'),
    path('comment_like/<int:pk>', views.comment_like, name='comment_like'),
    path('comment_dislike/<int:pk>', views.comment_dislike, name='comment_dislike'),
    path('save/<slug>', views.save, name='save')
]

top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('log_in', views.log_in, name='log_in'),
    path('log_out/', views.log_out, name='log_out')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='image.jpg', blank=True)
    likes = models.ManyToManyField(User, related_name='likes')
    dislikes = models.ManyToManyField(User, related_name='dislikes')
    comments_allowed = models.BooleanField(default=True)
    saved = models.ManyToManyField(User, related_name='saved_posts')

    def __str__(self):
        return self.title

    def snippet(self):
        return self.text[:20] + '...читать далее'

    def likes_counter(self):
        return self.likes.count()

    def dislikes_counter(self):
        return self.dislikes.count()


class Person(models.Model):
    name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes')
    dislikes = models.ManyToManyField(User, related_name='comment_dislikes')
    # ------
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    # ------
    def __str__(self):
        return f"{self.post} - {self.body[:15]}"

blog/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'input'}
    ), label='Название поста')
    text = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'textarea', 'size': '20'}
    ), label='Текст поста')

    image = forms.ImageField(label='Картинка для поста', required=False)
    comments_allowed = forms.CharField(
        widget=forms.CheckboxInput(),
        label='Комментирование разрешено',
        initial=True,
        required=False
    )

    class Meta:
        model = Post
        fields = ['title', 'text', 'image', 'comments_allowed']


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'textarea',
        'size': '40',
        'placeholder': 'Оставьте свой комментарий...'
    }))

    class Meta:
        model = Comment
        fields = ['body', ]

blog/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import *
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.contrib.auth.models import User
from django.core.paginator import Paginator


@login_required(login_url='/users/log_in')
def home(request):
    search = request.GET.get('search')
    my_posts = request.GET.get('my_posts')
    favorites = request.GET.get('favorites')
    popular = request.GET.get('popular')
    new = request.GET.get('new')
    show_author = request.GET.get('show_author')
    saved = request.GET.get('saved')
    posts = Post.objects.all()

    posts = posts.filter(author=show_author) if show_author else posts

    posts = posts.filter(saved=request.user) if saved else posts
    posts = posts.filter(likes=request.user) if favorites else posts
    posts = posts.filter(author=request.user) if my_posts else posts
    # posts = posts.filter(likes__gte=1) if popular else posts
    posts = Post.objects.annotate(like_count=Count('likes')).order_by('-like_count')[:3] \
        if popular else posts

    posts = posts.order_by('-date')[:3] if new else posts
    posts = posts.filter(likes=request.user) if favorites else posts

    if search:
        posts = Post.objects.filter(
            Q(title__icontains=search) |
            Q(text__icontains=search))

    pages = Paginator(posts, 2)
    page = request.GET.get('page')
    posts = pages.get_page(page)
    return render(request, 'home.html', {'posts': posts})


@login_required(login_url='/users/log_in')
def post(request, slug):
    post_detail = Post.objects.get(slug=slug)
    # -----
    parent_id = request.POST.get('parent_id')
    # ----
    form = CommentForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.post = post_detail
        # -----
        if parent_id:
            instance.parent = Comment.objects.get(pk=parent_id)
        # ----
        instance.save()
        return redirect('blog:post', slug=slug)
    return render(
        request,
        'post.html',
        {'post': post_detail, 'form': form}
    )


@login_required(login_url='/users/log_in')
def create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)

        if Post.objects.last():
            instance.slug = request.POST.get(
                'title') + str(Post.objects.last().pk + 1)
        else:
            instance.slug = request.POST.get('title')

        instance.author = request.user
        instance.save()
        return redirect('blog:home')
    return render(request, 'create.html', {'form': form})


@login_required(login_url='/users/log_in')
def delete_post(request, slug):
    post_data = Post.objects.get(slug=slug)

    if post_data.author != request.user:
        return HttpResponse('<h1>404 Error</h1>', status=404, reason='Delete post')

    if request.method == 'POST':
        post_data.delete()
        return redirect('blog:home')
    return render(request, 'delete_post.html', {'post': post_data})


@login_required(login_url='/users/log_in')
def edit_post(request, slug):
    post_data = Post.objects.get(slug=slug)
    form = PostForm(request.POST or None,
                    request.FILES or None,
                    instance=post_data)

    if post_data.author != request.user:
        return render(request, 'error.html', {'edit_post': True})

    if form.is_valid():
        form.save()
        return redirect('blog:post', slug=slug)
    return render(request,
                  'edit_post.html',
                  {'form': form, 'post': post_data})


def like(request, slug):
    post_data = Post.objects.get(slug=slug)
    target = 'likes'
    user = req

    b = f"post.{target}.all()"
    c = f'post.{target}.{"remove" if user in eval(b) else "add"}(user)'
    eval(c)
    return redirect('blog:post', slug=slug)


def dislike(request, slug):
    post_data = Post.objects.get(slug=slug)

    if request.user not in post_data.dislikes.all():
        post_data.dislikes.add(request.user)
        post_data.likes.remove(request.user)
    elif request.user in post_data.dislikes.all():
        post_data.dislikes.remove(request.user)
    return redirect('blog:post', slug=slug)


def comment_delete(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.method == 'POST':
        comment.delete()
        return redirect('blog:post', slug=comment.post.slug)
    return render(request, 'comment_delete.html', {'post': comment.post})


def comment_edit(request, pk):
    comment = Comment.objects.get(pk=pk)
    form = CommentForm(request.POST or None, instance=comment)

    if form.is_valid() and request.method == "POST":
        form.save()
        return redirect('blog:post', slug=comment.post.slug)
    return render(request,
                  'comment_edit.html',
                  {'form': form, 'post': comment.post})


def comment_like(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.user not in comment.likes.all():
        comment.likes.add(request.user)
        comment.dislikes.remove(request.user)
    elif request.user in comment.likes.all():
        comment.likes.remove(request.user)
    return redirect('blog:post', slug=comment.post.slug)


def comment_dislike(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.user not in comment.dislikes.all():
        comment.dislikes.add(request.user)
        comment.likes.remove(request.user)
    elif request.user in comment.dislikes.all():
        comment.dislikes.remove(request.user)
    return redirect('blog:post', slug=comment.post.slug)


def save(request, slug):
    post_data = Post.objects.get(slug=slug)

    post_data.saved.add(request.user) \
        if request.user not in post_data.saved.all() \
        else post_data.saved.remove(request.user)
    return redirect('blog:post', slug=post_data.slug)

blog/templates/base_layout.html
{% load static from static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>

<body>
    <section class="hero is-primary is-fullheight">
        {% if user.is_authenticated %}
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="{% url 'blog:home' %}">
                            <img src="https://msk.top-academy.ru/dist/images/logo/step_logo_rus.svg" alt="Logo">
                        </a>
                        <span class="navbar-burger" data-target="navbarMenuHeroA">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-start">
                            <span class="navbar-item">
                                <a href="{% url 'blog:create' %}" class="button is-info is-outlined is-inverted">
                                    <span class="mr-2">
                                        <ion-icon name="book-outline"></ion-icon>
                                    </span>
                                    <span class="content">Создать пост</span>
                                </a>
                            </span>
                        </div>
                        <!-- показать все посты этого автора -->
                        <div class="navbar-end">
                            <span class="navbar-item">
                                <div class="dropdown is-hoverable">
                                    <div class="dropdown-trigger">
                                        <a class="button is-info">
                                            Добро пожаловать, {{ request.user|title }}
                                        </a>
                                    </div>
                                    <div class="dropdown-menu">
                                        <div class="dropdown-content">
                                            {% if request.path == '/blog/home/' %}

                                            {% if user.post_set.all %}
                                            <span class="dropdown-item">
                                                <a href="{% url 'blog:home' %}?my_posts=True">
                                                    Мои посты
                                                </a>
                                            </span>
                                            {% endif %}

                                            {% if user.saved_posts.all %}
                                            <span class="dropdown-item">
                                                <a href="{% url 'blog:home' %}?saved=True">
                                                    Сохраненные
                                                </a>
                                            </span>
                                            {% endif %}
                                            
                                            {% if user.likes.all %}
                                            <a href="{% url 'blog:home' %}?favorites=True" class="dropdown-item">
                                                Избранное
                                            </a>
                                            {% endif %}

                                            <a href="{% url 'blog:home' %}?popular=True" class="dropdown-item">
                                                Популярные посты
                                            </a>
                                            <a href="{% url 'blog:home' %}?new=True" class="dropdown-item">
                                                Новые посты
                                            </a>
                                            {% endif %}
                                            <hr class="dropdown-divider">
                                            <span class="dropdown-item">
                                                <a href="{% url 'users:log_out' %}" class="has-text-danger">
                                                    Выйти
                                                </a>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </span>

                            {% if request.path == '/blog/home/' %}
                            <span class="navbar-item">
                                <form method="get" class="mt-4">
                                    <div class="field has-addons">
                                        <div class="control">
                                            <input type="search" class="input" name="search">
                                        </div>
                                        <div class="control">
                                            <button class="button" type="submit">
                                                <ion-icon name="search-outline"></ion-icon>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </span>
                            {% endif %}



                        </div>
                    </div>
                </div>
            </nav>
        </div>
        {% endif %}

        <div class="hero-body">
            {% block content %}

            {% endblock %}
        </div>
    </section>
</body>

</html>

blog/templates/comment_delete.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<form method="post" class="site-form has-background-light">
    {% csrf_token %}
    <p class="title has-text-centered is-4 mb-5 has-text-black">
        Подтвердите удаление комментария
    </p>
    <div class="has-text-centered">
        <button class="button is-danger">Подтвердить</button>
        <a class="button is-warning" href="{% url 'blog:post' post.slug %}">
            Назад к посту
        </a>
    </div>
</form>
{% endblock %}

blog/templates/comment_edit.html
{% extends 'base_layout.html' %}

{% block content %}
<form method="post" class="site-form has-background-light comment" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="has-text-centered mt-4">
        <button class="button is-success" type="submit">Сохранить</button>
        <a class="button is-danger" href="{% url 'blog:post' post.slug %}">
            Назад к посту
        </a>
    </div>
</form>
{% endblock %}

blog/templates/create.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<form class="site-form has-background-light" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="has-text-centered my-3">
        <button type="submit" class="button is-success">
            Отправить
        </button>
        <a href="{% url 'blog:home' %}" class="button is-warning">
            Назад
        </a>
    </div>
</form>
{% endblock %}

blog/templates/delete_post.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<form method="post" class="site-form has-background-light">
    {% csrf_token %}
    <p class="title has-text-centered is-4 mb-5 has-text-black">
        Подтвердите удаление поста "{{ post }}"
    </p>
    <div class="has-text-centered">
        <button class="button is-danger">Подтвердить</button>
        <a class="button is-warning" href="{% url 'blog:post' post.slug %}">
            Назад к посту
        </a>
    </div>
</form>
{% endblock %}

blog/templates/edit_post.html
{% extends 'base_layout.html' %}

{% block content %}
<form method="post" class="site-form has-background-light" enctype="multipart/form-data">
    <p class="title has-text-centered is-4 mb-5 has-text-black">
        Изменение поста "{{ post }}"
    </p>
    {% csrf_token %}
    {{ form }}
    <div class="has-text-centered">
        <button class="button is-success" type="submit">Сохранить</button>
        <a class="button is-danger" href="{% url 'blog:post' post.slug %}">
            Назад к посту
        </a>
    </div>
</form>
{% endblock %}

blog/templates/error.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="container">
    <div class="columns is-centered">
        <div class="column is-5">
            <div class="notification has-text-centered" >
                {% if delete_post %}
                <div class="subtitle has-text-black">Вы не можете удалить этот пост</div>
                {% endif %}
                {% if edit_post %}
                <div class="subtitle has-text-black">Вы не можете отредактировать этот пост</div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/home.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<div class="container">
    <div class="columns is-centered is-multiline">
        {% for post in posts %}
        <div class="column is-3">
            <a href="{% url 'blog:post' post.slug %}">
                <div class="card has-text-centered">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <div class="title has-text-black is-2">
                                    {{ post }}
                                </div>
                                {% if user == post.author %}
                                <div class="subtitle has-text-grey">
                                    Опубликовано Вами
                                </div>
                                {% else %}
                                <div class="subtitle has-text-grey">
                                    Опубликовано {{ post.author }}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="content">
                            {{ post.snippet }}
                            <br>
                            <div>{{ post.date }}</div>

                            <div class="columns" style="color: red">
                                <div class="column is-2">
                                    <div
                                        class="columns is-gapless is-flex is-justify-content-center is-align-items-center">
                                        <div class="column">
                                            <ion-icon name="heart-outline"></ion-icon>
                                        </div>
                                        <div class="column">
                                            <span class="ml-2">{{ post.likes_counter }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="column is-2">
                                    <div
                                        class="columns is-gapless is-flex is-justify-content-center is-align-items-center">
                                        <div class="column">
                                            <ion-icon name="heart-dislike-outline"></ion-icon>
                                        </div>
                                        <div class="column">
                                            <span class="ml-2">{{ post.dislikes_counter }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    {% if posts.has_other_pages %}
    <nav class="pagination is-centered">
        {% if posts.has_previous %}
        <a class="pagination-previous" href="?page={{posts.previous_page_number}}">
            Пред
        </a>
        <a class="pagination-link" href="?page=1">
            В начало
        </a>
        {% else %}
        <button class="pagination-previous" disabled>
            Пред
        </button>
        {% endif %}

        {% if posts.has_next %}
        <a class="pagination-next" href="?page={{ posts.next_page_number }}">
            Далее
        </a>
        <a href="?page={{ posts.paginator.num_pages }}" class="pagination-next">
            В конец
        </a>
        {% else %}
        <button class="pagination-next" disabled>
            Далее
        </button>
        {% endif %}

        <ul class="pagination-list">
            {% for page in posts.paginator.page_range %}
            <li>
                <a class="pagination-link 
                {% if page == posts.number %} is-current {% endif %}" href="?page={{page}}">{{ page }}</a>
            </li>
            {% endfor %}
        </ul>


    </nav>
    {% endif %}
</div>
{% endblock %}

blog/templates/post.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <div class="box has-text-centered" style="min-width: 100%">
        <div class="has-text-right">
            <a href="{% url 'blog:save' post.slug %}"
               class="button {% if user in post.saved.all %} is-success {% endif %}">
                <ion-icon name="bookmark-outline"></ion-icon>
            </a>
            {% if user == post.author %}
                <a href="{% url 'blog:edit_post' post.slug %}" class="button is-info">
                    <ion-icon name="create-outline"></ion-icon>
                </a>
                <a href="{% url 'blog:delete_post' post.slug %}" class="button is-danger">
                    <ion-icon name="trash-outline"></ion-icon>
                </a>
            {% else %}
                <p class="content has-text-grey">
                    Редактирование/удаление поста недоступно
                </p>
            {% endif %}
        </div>
        <div class="title has-text-black">
            {{ post }}
        </div>

        {% if post.image %}
            <img src="{{ post.image.url }}" alt="" class="image is-centered post-image">
        {% else %}
            <img src="{% static 'images/image.jpg' %}" alt="" class="image is-centered post-image">
        {% endif %}
        <div class="subtitle has-text-black">
            {{ post.text }}
        </div>
        <p class="content has-text-right is-italic">
            {% if user == post.author %}
                Вы
            {% else %}
                <a href="{% url 'blog:home' %}?show_author={{ post.author.id }}" class="button is-ghost">
                    {{ post.author }}
                </a>
            {% endif %}
            : {{ post.date }}
        </p>


        <div class="columns is-gapless">
            <form method="post" class="has-text-right" action="{% url 'blog:like' post.slug %}">
                {% csrf_token %}
                <button class="button {% if user in post.likes.all %} is-success {% endif %}" type="submit">
                    <ion-icon name="thumbs-up-outline"></ion-icon>
                    <span class="ml-3">
                    {{ post.likes_counter }}
                </span>
                </button>
            </form>
            <form method="post" class="has-text-right" action="{% url 'blog:dislike' post.slug %}">
                {% csrf_token %}
                <button class="button {% if user in post.dislikes.all %} is-danger {% endif %}" type="submit"
                        type="submit">
                    <ion-icon name="thumbs-down-outline"></ion-icon>
                    <span class="ml-3">
                    {{ post.dislikes_counter }}
                </span>
                </button>
            </form>
        </div>
        {% if post.comments_allowed %}
            <form method="post" enctype="multipart/form-data" class="comment has-text-left">
                {% csrf_token %}
                {{ form }}
                <button class="button is-success my-4">
                    Отправить
                </button>
            </form>
            {% if not post.comment_set.all %}
                <div class="has-text-centered has-text-grey-light subtitle is-5 my-4">
                    0 комментариев
                </div>

            {% else %}
                <p class="has-text-centered is-size-3 mb-6">
                    Комментарии
                </p>
                <div class="columns is-multiline is-centered">
                    {% for comment in post.comment_set.all %}
                        <div class="column is-5">
                            <article class="message is-info">
                                <div class="message-header">
{#                                   ---------#}
                                    {% if comment.parent %}
                                        В ответ на {{ comment.parent }} от {{ comment.parent.user }}
                                        <br>
                                    {% endif %}
{#                                -------#}
                                    Добавлено {{ comment.user }} в {{ comment.date }}
                                    <div class="buttons has-addons is-right">
                                        <a href="{% url 'blog:comment_delete' comment.pk %}" class="button is-small">
                                            <ion-icon name="trash-outline"></ion-icon>
                                        </a>
                                        <a href="{% url 'blog:comment_edit' comment.pk %}" class="button is-small">
                                            <ion-icon name="create-outline"></ion-icon>
                                        </a>
                                    </div>
                                </div>
                                <div class="message-body">
                                    {{ comment.body }}
                                    <form method="post" enctype="multipart/form-data" class="comment has-text-left">
                                        {% csrf_token %}
                                        {{ form }}
                                        <input type="hidden" name="parent_id" value="{{ comment.pk }}">
                                        <button class="button is-success my-4">
                                            Отправить
                                        </button>
                                    </form>

                                    <div class="buttons is-right">
                                        <a href="{% url 'blog:comment_like' comment.pk %}"
                                           class="button {% if user in comment.likes.all %} is-success {% endif %}">
                                            <ion-icon name="thumbs-up-outline"></ion-icon>
                                        </a>

                                        <a href="{% url 'blog:comment_dislike' comment.pk %}"
                                           class="button {% if user in comment.dislikes.all %} is-danger {% endif %}">
                                            <ion-icon name="thumbs-down-outline"></ion-icon>
                                        </a>
                                    </div>
                                </div>
                            </article>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}